name: Terraform Apply

on:
  workflow_call:
    inputs:
      working-directory:
        description: The directory of the Terraform configuration
        type: string
        required: true
    secrets:
      TF_TOKEN_APP_TERRAFORM_IO:
        description: The Terraform Cloud API token
        required: true
      localAdminPassword:
        required: true
      domainAdminPassword:
        required: true
      deploymentUserPassword:
        required: true
      servicePrincipalSecret:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  terraform-apply:
    runs-on: terraform-cloud
    environment: Production
    env:
      TF_ORGANIZATION: ${{ vars.TF_ORGANIZATION }}
      TF_TOKEN_APP_TERRAFORM_IO: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}
      ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
      ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
      ARM_USE_OIDC: true
      TF_VAR_subscription_id: ${{ vars.ARM_SUBSCRIPTION_ID }}
      TF_VAR_local_admin_user: ${{ vars.localAdminUser }}
      TF_VAR_hci_0_local_admin_user: ${{ vars.localAdminUser }}
      TF_VAR_local_admin_password: ${{ secrets.localAdminPassword }}
      TF_VAR_hci_0_local_admin_password: ${{ secrets.localAdminPassword }}
      TF_VAR_domain_admin_user: ${{ vars.domainAdminUser }}
      TF_VAR_domain_admin_password: ${{ secrets.domainAdminPassword }}
      TF_VAR_deployment_user_password: ${{ secrets.deploymentUserPassword }}
      TF_VAR_hci_0_deployment_user_password: ${{ secrets.deploymentUserPassword }}
      TF_VAR_service_principal_id: ${{ vars.servicePrincipalId }}
      TF_VAR_hci_0_service_principal_id: ${{ vars.servicePrincipalId }}
      TF_VAR_service_principal_secret: ${{ secrets.servicePrincipalSecret }}
      TF_VAR_hci_0_service_principal_secret: ${{ secrets.servicePrincipalSecret }}
      TF_VAR_rp_service_principal_object_id: ${{ vars.rpServicePrincipalObjectId }}
      TF_VAR_vm_admin_password: ${{ secrets.localAdminPassword }}
      TF_VAR_domain_join_password: ${{ secrets.domainAdminPassword }}
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - uses: azure/login@v2
        with:
          client-id: ${{ vars.ARM_CLIENT_ID }}
          tenant-id: ${{ vars.ARM_TENANT_ID }}
          allow-no-subscriptions: true

      - uses: wegmans/actions/terraform/unlock-azure-resources@v1
        with:
          working-directory: ${{ inputs.working-directory }}

      - uses: wegmans/actions/terraform/apply@v1
        with:
          working-directory: ${{ inputs.working-directory }}